class_name LocEn
## Английский перевод (18.09.2026). Ключ — русская строка РОВНО как в коде
## (Loc.t("…") и таблицы-константы), значение — английская. Порядок и число
## подстановок %d/%s в переводе обязаны совпадать с ключом. Полноту
## проверяет `py tools/loc_keys.py` (печатает ключи без перевода).
## Длину держать близкой к русской: таблички и кнопки фиксированной ширины.

const EN := {
	# ---- Гараж (CarSelect) ----
	"ПОДКЛЮЧЕНИЕ…": "CONNECTING…",
	"ЗАГРУЗКА…": "LOADING…",
	"НАЖМИТЕ, ЧТОБЫ НАЧАТЬ": "TAP TO START",
	"К КОМАНДЕ…": "JOINING TEAM…",
	"ОБНОВИТЕ ИГРУ": "UPDATE THE GAME",
	"ИЩЕМ ЗАЕЗД…": "FINDING RACE…",
	"ГОТОВ ✓ · ЖДЁМ КОМАНДУ": "READY ✓ · WAITING FOR TEAM",
	"ГОТОВ": "READY",
	"СТАРТ": "START",
	"Заезд не ответил — нажмите «ГОТОВ» ещё раз": "The race did not respond — press READY again",
	"Имя «%s» уже занято — попробуй другое": "The name “%s” is taken — try another one",
	"Сервер не принял имя, попробуй другое": "The server rejected the name, try another one",
	"%s зовёт тебя в команду (%d чел.)": "%s invites you to a team (%d players)",
	"ПРИНЯТЬ": "ACCEPT",
	"ОТКЛОНИТЬ": "DECLINE",
	"РЕЖИМ": "MODE",
	"ГОНКА": "RACE",
	"ФУТБОЛ": "SOCCER",
	"ИМЯ: %s": "NAME: %s",
	"версия игры устарела": "game version is outdated",
	"друзья: на связи, имя не принято": "friends: online, name rejected",
	"на связи, друзей пока нет": "online, no friends yet",
	"на связи, друзья: …": "online, friends: …",
	"друзей в сети: %d из %d": "friends online: %d of %d",
	"друзья: имя занято": "friends: name is taken",
	"друзья: нет сети на устройстве": "friends: device is offline",
	"друзья: нет связи с сервером": "friends: no server connection",
	"КАК ТЕБЯ ЗОВУТ?": "WHAT'S YOUR NAME?",
	"Имя «%s» уже занято другим игроком — выбери другое": "The name “%s” is taken by another player — pick another one",
	"Под этим именем тебя увидят другие игроки. Имена уникальны": "Other players will see you under this name. Names are unique",
	"твоё имя": "your name",
	"ГОТОВО": "DONE",
	"ОТМЕНА": "CANCEL",
	"введи хоть что-нибудь": "type something",
	"Проверяем имя…": "Checking the name…",
	"Досмотри два ролика подряд — +%d монет.\nПотом 10 минут отдыха.": "Watch two ads in a row — +%d coins.\nThen a 10-minute break.",
	"ИДЁТ РОЛИК…": "AD IS PLAYING…",
	"+%d ЗА РЕКЛАМУ": "+%d FOR AN AD",
	"ЕЩЁ РОЛИК · +%d": "ONE MORE AD · +%d",
	"ЧЕРЕЗ %d:%02d": "IN %d:%02d",
	# Ежедневный вход (23.09).
	"ЕЖЕДНЕВНАЯ НАГРАДА": "DAILY REWARD",
	"Заходи каждый день — награда растёт. Пропустишь день — неделя сначала": "Come back every day — the reward grows. Miss a day and the week restarts",
	"ДЕНЬ %d": "DAY %d",
	"ЗАБРАТЬ +%s": "COLLECT +%s",
	"РЕКЛАМА": "AD",
	"Ролик %d из %d · на Яндекс Играх здесь идёт видео": "Ad %d of %d · a video plays here on Yandex Games",
	"Досмотри ролик — опыт и монеты заезда начислятся ещё раз": "Watch an ad to the end — the race XP and coins are granted once more",
	"Реклама не загрузилась": "The ad did not load",
	"Удвоение наград заезда · на Яндекс Играх здесь идёт видео": "Doubling race rewards · a video plays here on Yandex Games",
	"С %d УРОВНЯ · %s": "FROM LEVEL %d · %s",
	"КУПИТЬ · %s": "BUY · %s",
	"НЕ ХВАТАЕТ МОНЕТ": "NOT ENOUGH COINS",
	"УРОВЕНЬ %d": "LEVEL %d",
	"%s — с %d уровня, %s монет": "%s — from level %d, %s coins",
	"СТЕНД · ТЕСТОВЫЙ ПРОФИЛЬ · ВАШ ПРОГРЕСС ЦЕЛ": "TEST RIG · TEST PROFILE · YOUR PROGRESS IS SAFE",
	"ТЕСТОВЫЙ СЕРВЕР · порт %d": "TEST SERVER · port %d",
	"СЕТИ НЕТ · ЗАЕЗД С БОТАМИ": "OFFLINE · RACE WITH BOTS",
	"ОБНОВИТЕ ИГРУ · ВЕРСИЯ УСТАРЕЛА": "UPDATE THE GAME · VERSION OUTDATED",
	" тест": " test",
	"Пыль и Пламя — СТЕНД (тестовый профиль)": "Dust and Flame — TEST RIG (test profile)",
	"Пыль и Пламя — ТЕСТОВЫЙ СЕРВЕР": "Dust and Flame — TEST SERVER",
	"МАГАЗИН": "SHOP",
	"КОМАНДА": "TEAM",
	"СТАТИСТИКА": "STATS",
	"АВТОПАРК": "CARS",
	"ОРУЖИЕ": "WEAPONS",
	"ТЮНИНГ": "TUNING",
	"ЗАКРЫТЬ": "CLOSE",
	"%d ур.": "lvl %d",
	# Названия машин.
	"Копейка": "Kopeyka",
	"Двойка": "Dvoyka",
	"Нива": "Niva",
	"Тройка": "Troyka",
	"Четвёрка": "Chetvyorka",
	"Пятёрка": "Pyatyorka",
	"Шестёрка": "Shestyorka",
	"Семёрка": "Semyorka",
	"Пятёрка Спорт": "Pyatyorka Sport",
	"Зубило": "Zubilo",
	"Девятка": "Devyatka",
	"Самара 99": "Samara 99",
	"Волга 21": "Volga 21",
	"Волга 24": "Volga 24",
	"Нива Лонг": "Niva Long",
	"Стрела": "Arrow",
	"Сарай": "Wagon",
	"Багги": "Buggy",
	"Малыш": "Tiny",
	"Пикап": "Pickup",
	"Монстр": "Monster",
	"Маслкар": "Muscle Car",
	"Кирпич": "Brick",
	"Игрок": "Player",
	"Игрок %d": "Player %d",
	"Бот %d": "Bot %d",

	# ---- Лобби ----
	"ЛОББИ": "LOBBY",
	"Подключение…": "Connecting…",
	"✕ — в гараж": "✕ — to garage",
	"Подключается…": "Connecting…",
	"Ждём игрока…": "Waiting for a player…",
	" — ты": " — you",
	" · друг": " · friend",

	# ---- Заезд (Main) ----
	"СЕТИ НЕТ": "OFFLINE",
	"заезд с ботами": "race with bots",
	"НЕТ СВЯЗИ С СЕРВЕРОМ": "NO SERVER CONNECTION",
	"возьми бокс": "grab a box",
	"КРУГ %d/%d": "LAP %d/%d",
	"МЕСТО %d/%d": "POS %d/%d",
	"В ГАРАЖ": "GARAGE",
	"ФИНИШ!  МЕСТО %d ИЗ %d": "FINISH!  PLACE %d OF %d",
	"ОПЫТА": "XP",
	"МОНЕТ": "COINS",
	"НОВЫЙ УРОВЕНЬ %d!": "NEW LEVEL %d!",
	"ГОНЩИК": "RACER",
	"ВРЕМЯ": "TIME",
	"ЛУЧШИЙ КРУГ": "BEST LAP",
	"не доехал": "DNF",
	"едет…": "racing…",
	"РЕКОРД КРУГА": "LAP RECORD",
	"пока нет": "none yet",
	"РЕКОРД ГОНКИ": "RACE RECORD",
	"★ НОВЫЙ": "★ NEW",
	"РЕКОРД КРУГА!": "LAP RECORD!",
	"РЕКОРД ГОНКИ!": "RACE RECORD!",
	"Вне трассы!": "Off the track!",
	"Перевернулся!": "Flipped over!",
	"Застрял!": "Stuck!",
	"%s Возврат через %d…": "%s Respawn in %d…",
	"КМ/Ч": "KM/H",
	"км/ч": "km/h",
	"КРУГ 1/%d": "LAP 1/%d",
	"МЕСТО 1/4": "POS 1/4",
	"ENTER — В ГАРАЖ": "ENTER — TO GARAGE",
	"WASD — движение | Space — ручник | Shift — прыжок | E — оружие | R — на трассу | Esc — меню": "WASD — drive | Space — handbrake | Shift — jump | E — weapon | R — respawn | Esc — menu",
	"Связь с сервером потеряна.\nВозвращаемся в гараж…": "Connection to the server lost.\nReturning to the garage…",
	"Сервер не выдал слот.\nВозможно, версии игры различаются — обновите игру.\nEsc — в гараж": "The server gave no slot.\nGame versions may differ — update the game.\nEsc — to garage",
	"Здесь всё занято — едем в свободный заезд…": "This one is full — moving to a free race…",
	"Сервер не ответил": "The server did not respond",
	"Заезд не ответил — возвращаемся к воротам…": "The race did not respond — returning to the gate…",
	"Esc — в гараж": "Esc — to garage",
	"Заезд уже идёт — в него не влезть.\nЖдём следующего: начнётся, как только эта гонка закончится.": "The race is already running — can't join it.\nWaiting for the next one: it starts as soon as this race ends.",
	"Все в сборе — поехали!": "Everyone is here — let's go!",
	"Игроков: %d/%d": "Players: %d/%d",
	"Ждём игроков…": "Waiting for players…",
	"Ждём твою команду…": "Waiting for your team…",
	"Ждём, пока у всех загрузится…": "Waiting for everyone to load…",
	"Управление сбито: лево и право поменялись!": "Controls scrambled: left and right are swapped!",
	"ПЕРВАЯ КРОВЬ!": "FIRST BLOOD!",
	"ДВОЙНОЕ УБИЙСТВО!": "DOUBLE KILL!",
	"ТРОЙНОЕ УБИЙСТВО!": "TRIPLE KILL!",
	"Вас уничтожил %s": "Destroyed by %s",
	"%s уничтожен!": "%s destroyed!",
	"ПОСЛЕДНИЙ КРУГ!": "FINAL LAP!",
	"ВЫ ЛИДЕР!": "YOU LEAD!",
	"Лидерство потеряно": "Lead lost",
	"Не удалось начать подключение: %s": "Could not start connecting: %s",
	# Тексты, которые сервер заезда шлёт целиком (см. Loc.server).
	"Все заезды заняты — попробуй через минуту.": "All races are full — try again in a minute.",
	"Свободный заезд не нашёлся — попробуй через минуту.": "No free race found — try again in a minute.",

	# ---- Команда друзей (PartyPanel) ----
	"КОМАНДА ДРУЗЕЙ": "FRIENDS TEAM",
	"ДРУЗЬЯ": "FRIENDS",
	"имя друга": "friend's name",
	"НАЙТИ": "FIND",
	"ВЫЙТИ": "LEAVE",
	"Нет связи с сервером друзей": "No connection to the friends server",
	"Никого не нашлось": "Nobody found",
	"Сейчас никого нет в игре": "Nobody is in the game right now",
	"не в сети": "offline",
	"в заезде": "in a race",
	"в гараже": "in the garage",
	", в команде": ", in a team",
	"ПРИГЛАСИТЬ": "INVITE",
	"ДРУЗЬЯ (%d)": "FRIENDS (%d)",
	"Пока никого: найди друга ниже и пригласи — он останется здесь": "Nobody yet: find a friend below and invite them — they will stay here",
	"Убрать из списка": "Remove from the list",
	"Нет связи с сервером друзей — проверь интернет или подожди: подключаемся…": "No connection to the friends server — check your internet or wait: connecting…",
	"Имя «%s» занято другим игроком — нажми «ИМЯ» вверху и выбери другое": "The name “%s” is taken by another player — press NAME at the top and pick another",
	"Сначала введи имя (кнопка «ИМЯ» вверху)": "Enter your name first (the NAME button at the top)",
	"На связи как «%s». Зови друзей (до %d чел.); все нажали «ГОТОВ» — едете в один заезд.": "Online as “%s”. Invite friends (up to %d players); once everyone presses READY you go into one race.",
	"В КОМАНДЕ: %d/%d": "IN TEAM: %d/%d",
	"Команды пока нет — пригласи друга": "No team yet — invite a friend",
	"ГОТОВ ✓ — ждём остальных": "READY ✓ — waiting for others",
	"Ищем заезд…": "Finding a race…",
	" (ты)": " (you)",
	"ГОТОВ ✓": "READY ✓",
	"ждёт": "waiting",
	"Обновите игру": "Update the game",

	# ---- Футбол ----
	"ПОСЛЕДНЯЯ МИНУТА": "LAST MINUTE",
	"вы": "you",
	"автогол! (%s)": "own goal! (%s)",
	"забил: %s": "scored by: %s",
	"ГОЛ! Счёт %d : %d": "GOAL! Score %d : %d",
	"ИГРА!": "PLAY!",
	"Мяч вылетел — вбрасывание в центре": "Ball out — drop at the center",
	"ПОБЕДА СИНИХ %d : %d": "BLUE WINS %d : %d",
	"ПОБЕДА КРАСНЫХ %d : %d": "RED WINS %d : %d",
	"НИЧЬЯ %d : %d": "DRAW %d : %d",
	"опыт +%d  ·  монеты +%d": "XP +%d  ·  coins +%d",
	"Вас заморозили!": "You are frozen!",
	"Вас притянуло магнитом!": "Pulled by a magnet!",
	"Вас разбил красный щит!": "Wrecked by a red shield!",
	"лови бонус": "grab a bonus",
	"Enter — в гараж": "Enter — to garage",
	"WASD/стрелки — езда  |  Ctrl/J — оружие  |  Shift — прыжок  |  Space — ручник  |  R — на место  |  Esc — в гараж": "WASD/arrows — drive  |  Ctrl/J — weapon  |  Shift — jump  |  Space — handbrake  |  R — reset  |  Esc — to garage",
	"СИНИЕ": "BLUE",
	"КРАСНЫЕ": "RED",

	# ---- Статистика ----
	"СТАТИСТИКА · %s": "STATS · %s",
	"РЕЙТИНГ": "RATING",
	"УРОВЕНЬ": "LEVEL",
	"ЗАЕЗДОВ": "RACES",
	"Рейтинг: старт %d, за победу +%d, за последнее место −%d, середина 0, плюс %d за каждого уничтоженного соперника.": "Rating: starts at %d, +%d for a win, −%d for last place, 0 for the middle, plus %d for every rival destroyed.",
	"ЛУЧШИЕ ИГРОКИ · ТОП-10": "BEST PLAYERS · TOP 10",
	"ГОНКИ": "RACES",
	"Заездов": "Races",
	"%d (по сети %d)": "%d (online %d)",
	"Побед": "Wins",
	"Подиумов (1–3 место)": "Podiums (places 1–3)",
	"Среднее место": "Average place",
	"Уничтожено соперников": "Rivals destroyed",
	"Уничтожали тебя": "Times destroyed",
	"Опыт": "XP",
	"%d (до уровня %d: %d / %d)": "%d (to level %d: %d / %d)",
	"ЛЮБИМАЯ МАШИНА": "FAVORITE CAR",
	"Проедь первый заезд — узнаем": "Finish your first race to find out",
	"заездов на ней: %d": "races in it: %d",
	"ещё: ": "also: ",
	"Матчей": "Matches",
	"Голов": "Goals",
	"нет сети на устройстве": "device is offline",
	"нет связи с сервером": "no server connection",
	"Таблица лучших недоступна: %s": "Leaderboard unavailable: %s",
	"Загрузка…": "Loading…",
	"Сервер не прислал таблицу — обновите сервер игры": "The server sent no leaderboard — update the game server",
	"Пока никто не проехал ни одного заезда": "Nobody has finished a race yet",
	"в сети": "online",
	"%d · заездов %d": "%d · races %d",
	"Тебя в таблице пока нет — проедь заезд, будучи на связи": "You are not on the board yet — finish a race while online",
	"Ты появишься в таблице после следующего заезда на связи": "You will appear on the board after your next online race",
	"Твоё место: %d из %d": "Your place: %d of %d",
	"Игроков в таблице: %d": "Players on the board: %d",

	# ---- Экранные кнопки ----
	"ГАЗ": "GAS",
	"ТОРМОЗ": "BRAKE",
	"БОНУС": "BONUS",

	# ---- Тюнинг ----
	"НУЖЕН %d УРОВЕНЬ": "LEVEL %d NEEDED",
	"наклейка №%d": "sticker #%d",
	"полоса": "stripe",
	"металлик %s": "metallic %s",
	"дым %s": "smoke: %s",
	"неон %s": "neon: %s",
	"стёкла %s": "glass: %s",
	"ПРИМЕРКА: %s": "TRYING ON: %s",
	"СБРОС": "RESET",
	"ТЮНИНГ · %s": "TUNING · %s",
	"МОНЕТЫ %s": "COINS %s",
	"Тюнинг — только внешний вид: на скорость, разгон и управляемость он не влияет. Клик по некупленному — примерить, покупка — кнопкой «КУПИТЬ» внизу; уйдёте на другую вкладку — примерка снимется.": "Tuning is looks only: it does not affect speed, acceleration or handling. Click an item you don't own to try it on, buy with the BUY button below; switching tabs removes the try-on.",
	"%s  куплено %d из %d   %s · три ступени: простые %s, средние %s, лучшие %s монет": "%s  owned %d of %d   %s · three tiers: basic %s, medium %s, best %s coins",
	"Родные колёса": "Stock wheels",
	"Пусто": "None",
	"Сток": "Stock",
	"Куплено · %s деталь": "Owned · %s part",
	"%s деталь — %s": "%s part — %s",
	"с %d уровня, %s монет — нажмите, чтобы примерить": "from level %d, %s coins — click to try on",
	"%s монет — нажмите, чтобы примерить": "%s coins — click to try on",
	"полосы": "stripe",
	"детали": "part",
	"ЦВЕТ %s   36 красок — бесплатно": "%s COLOR   36 paints — free",
	"АВТО": "AUTO",
	"РОДНОЙ": "STOCK",
	"КАК КУЗОВ": "AS BODY",
	"Цвет по кузову: тёмная полоса на светлом, светлая на тёмном": "Matches the body: dark stripe on light paint, light on dark",
	"КРАСКА   12 цветов × 3 оттенка — бесплатно": "PAINT   12 colors × 3 shades — free",
	"МЕТАЛЛИК  %d из %d   по %s за цвет · зеркальный блик и лак": "METALLIC  %d of %d   %s per color · mirror shine and lacquer",
	"Металлик · %s": "Metallic · %s",
	"Металлик · %s — %s": "Metallic · %s — %s",
	"У этой машины один цвет — перекрасить нельзя.": "This car has a single color — it can't be repainted.",
	"КРАСКА   %d цветов — бесплатно": "PAINT   %d colors — free",
	"ПОЛОСА   двойная полоса по кузову — %s": "STRIPE   double stripe over the body — %s",
	"ПОЛОСА: %s": "STRIPE: %s",
	"ВКЛ": "ON",
	"ВЫКЛ": "OFF",
	"ПРИМЕРЕНА · %s": "TRIED ON · %s",
	"ПРИМЕРИТЬ · %s": "TRY ON · %s",
	"Нажмите, чтобы примерить; купить — кнопкой «КУПИТЬ»": "Click to try on; buy with the BUY button",
	"НАКЛЕЙКИ  %d из %d   по %s за штуку": "STICKERS  %d of %d   %s each",
	"Без наклейки": "No sticker",
	"Куплено": "Owned",
	"%s  %d из %d   по %s за цвет · %s": "%s  %d of %d   %s per color · %s",
	"Куплено · %s": "Owned · %s",
	"МОТОР": "ENGINE",
	"КОЛЁСА": "WHEELS",
	"СПОЙЛЕР": "SPOILER",
	"ВЫХЛОП": "EXHAUST",
	"компрессоры на капот": "hood superchargers",
	"комплекты дисков": "rim sets",
	"спойлеры на корму": "rear spoilers",
	"выхлопы": "exhausts",
	"КРАСКА": "PAINT",
	"ПОЛОСА": "STRIPE",
	"НАКЛЕЙКИ": "STICKERS",
	"ЭФФЕКТЫ": "EFFECTS",
	"ДЫМ ИЗ-ПОД КОЛЁС": "TIRE SMOKE",
	"ОБЫЧНЫЙ": "NORMAL",
	"цветной дым в заносе, пламя выхлопа при ускорении": "colored drift smoke, exhaust flame on boost",
	"НЕОН ПОД ДНИЩЕМ": "UNDERGLOW NEON",
	"подсветка под машиной": "light under the car",
	"ТОНИРОВКА СТЁКОЛ": "WINDOW TINT",
	"РОДНЫЕ": "STOCK",
	"цвет стёкол": "glass color",
	"красный": "red",
	"оранжевый": "orange",
	"жёлтый": "yellow",
	"зелёный": "green",
	"бирюзовый": "turquoise",
	"голубой": "light blue",
	"синий": "blue",
	"фиолетовый": "purple",
	"розовый": "pink",
	"коричневый": "brown",
	"кремовый": "cream",
	"серый": "grey",
	"белый": "white",
	"чёрный": "black",
	"песочный": "sand",
	"простая": "basic",
	"средняя": "medium",
	"лучшая": "best",

	# ---- Магазин оружия ----
	"ОРУЖИЕ · ПРОКАЧКА": "WEAPONS · UPGRADES",
	"У каждого оружия три ступени — I, II, III. Покупаются по порядку за монеты, каждая открывается с определённого уровня. Само оружие по-прежнему выпадает из боксов на трассе; III ступень роняет его в полтора раза чаще. Уровень %d.": "Every weapon has three tiers — I, II, III. They are bought in order for coins, each unlocks at a certain level. The weapons still drop from boxes on the track; tier III makes them drop 1.5× more often. Level %d.",
	"Все ступени куплены.": "All tiers owned.",
	"МАКС": "MAX",
	"с %d ур.": "lvl %d",
	"Мина": "Mine",
	"Ракета": "Rocket",
	"Масло": "Oil",
	"Магнит": "Magnet",
	"Лазер": "Laser",
	"Заморозка": "Freeze",
	"Авиаудар": "Airstrike",
	"Ускорение": "Boost",
	"Глушилка": "Jammer",
	"Щит": "Shield",
	"лёгкое": "light",
	"среднее": "medium",
	"тяжёлое": "heavy",
	"взрыв шире на 15 %": "blast 15% wider",
	"две мины — под левое и правое колесо": "two mines — under the left and right wheels",
	"три мины в ряд": "three mines in a row",
	"ракета крупнее: попадание на 15 % шире": "bigger rocket: hit area 15% wider",
	"самонаведение — доворачивает на соперника рядом с курсом": "homing — steers toward a rival near its path",
	"летит за лидером гонки (если лидер ты — за вторым)": "chases the race leader (or second place if you lead)",
	"пятно на 15 % больше": "slick 15% bigger",
	"наехавшего заносит и крутит (без II — только замедляет)": "spins out whoever hits it (without II it only slows)",
	"пятно ещё больше": "even bigger slick",
	"рывок сильнее на 15 %": "pull 15% stronger",
	"жертвы теряют всю скорость": "victims lose all speed",
	"отдёргивает к себе и останавливает": "yanks rivals toward you and stops them",
	"луч шире на 15 %": "beam 15% wider",
	"бьёт через всю трассу — без предела дальности": "hits across the whole track — unlimited range",
	"луч держится в полтора раза дольше": "beam lasts 1.5× longer",
	"заморозка держится на 15 % дольше": "freeze lasts 15% longer",
	"ледышка летит на 20 % быстрее, заморозка на 1 с дольше": "ice shard flies 20% faster, freeze lasts 1 s longer",
	"заморозка ещё на 1 с дольше": "freeze lasts 1 more second",
	"четыре ракеты вместо двух, воронки шире на 15 %": "four rockets instead of two, craters 15% wider",
	"пять ракет, с упреждением по едущим впереди": "five rockets, leading the cars ahead",
	"шесть ракет с упреждением": "six rockets with lead",
	"ускорение держится на 15 % дольше": "boost lasts 15% longer",
	"ускорение держится в полтора раза дольше": "boost lasts 1.5× longer",
	"ускоряет сильнее": "stronger boost",
	"сбитое управление держится на 15 % дольше": "scrambled controls last 15% longer",
	"волна летит на 30 % быстрее": "wave travels 30% faster",
	"сбитое управление ещё на 1 с дольше": "scrambled controls last 1 more second",
	"щит держится на 15 % дольше": "shield lasts 15% longer",
	"жёлтый щит: коснувшийся соперник теряет скорость": "yellow shield: a rival touching it loses speed",
	"красный щит: коснувшийся соперник взрывается": "red shield: a rival touching it explodes",
}

## Тексты сервера с подставленными именами/числами: русский шаблон
## (%s, %d) → английский с {1}, {2}… по порядку групп (см. Loc.server).
const SERVER_PATTERNS := {
	"Версии игры не совпадают\n(у сервера %d, у тебя %d). Обновите игру.": "Game versions do not match\n(server {1}, yours {2}). Update the game.",
	"Обновите игру: у сервера версия %d, у вас %d. Пока версии не совпадут, играть нельзя.": "Update the game: server version {1}, yours {2}. You can't play until the versions match.",
	"Игрок «%s» не найден": "Player “{1}” not found",
	"Ты вышел из заезда, не доехав — дождись его окончания (ещё ~%d с).": "You left a race before finishing — wait for it to end (about {1} s left).",
	"%d секунд без движения — ты исключён из заезда.": "{1} seconds without moving — you were removed from the race.",
	"%s сейчас не в игре": "{1} is not in the game right now",
	"%s уже в твоей команде": "{1} is already in your team",
	"%s уже в другой команде": "{1} is already in another team",
	"В команде уже %d человек": "The team already has {1} players",
	"Приглашение отправлено: %s": "Invitation sent: {1}",
	"%s в команде": "{1} joined the team",
	"%s отклонил приглашение": "{1} declined the invitation",
	"%s вышел — команда распущена": "{1} left — the team is disbanded",
	"%s вышел из команды": "{1} left the team",
	"Профиль без идентификатора": "Profile has no ID",
	"Сначала подтверди своё имя": "Confirm your name first",
	"Себя приглашать не нужно": "No need to invite yourself",
	"Приглашение уже недействительно": "The invitation is no longer valid",
	"Команда уже распалась": "The team has already disbanded",
	"В команде уже нет места": "The team is already full",
	"Приглашение отклонено": "Invitation declined",
	"Все готовы — ищем заезд…": "Everyone is ready — finding a race…",
	"Поднимаем заезд для команды…": "Starting a race for the team…",
	"Все заезды заняты — попробуйте через минуту": "All races are full — try again in a minute",
}
